# Generated by Django 5.0 on 2024-02-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_type_id',
            new_name='staff_type',
        ),
    ]
