# Generated by Django 5.0 on 2024-02-22 14:01

from django.db import migrations


def load_data_from_sql():
    from hospital.settings import BASE_DIR
    import os
    sql_statements = open(os.path.join(BASE_DIR, 'app/sql/script.sql'), 'r').read()
    return sql_statements

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_person_id_patient_person_and_more'),
    ]

    operations = [
        migrations.RunSQL(load_data_from_sql()),
    ]
